### ISSUE TITLE
Getting error 401: Unauthorized while installing  

### ISSUE THREAD

**Issue by abhilash-shrivastava** [PredixDev/predix-rmd-ref-app#8]
After cloning the reference app and running the installation python script in the below manner from command line

python scripts/installRefApp.py

I am getting an HTTP error 401 : Unauthorized 

![reference app](https://cloud.githubusercontent.com/assets/13994709/14404831/884c6150-fe34-11e5-9d85-cb0f28d4f988.png)

**Comment by wushu123** [comment]
Hi, 
We released another version of the install script and mvn API key tutorial. Please login to the artifactory using your account and get the API key for installing your reference application.

Please go to this tutorial on how to get API key from the artifactory. 

https://www.predix.io/resources/tutorials/tutorial-details.html?tutorial_id=1560&tag=1608&journey=Development%20tools%20and%20tips&resources=1565,1560,1727

Please let me know if you have further issues.

**Comment by turnerth** [comment]
I have a feeling you forgot to add your encrypted password to your ~/.m2/settings.xml.  Please review the tutorial setup instructions.
